# Generated by Django 2.2.1 on 2019-05-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equation_solver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equation_solver',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='equation_solver',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equation_solver',
            name='variables',
            field=models.TextField(),
        ),
    ]
