# Generated by Django 2.2.1 on 2019-05-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equation_solver', '0002_auto_20190525_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
