# Generated by Django 2.2.1 on 2019-05-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equation_solver', '0005_equation_solver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equation_solver',
            name='number',
        ),
    ]
