# Generated by Django 2.2.1 on 2019-06-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equation_solver', '0006_remove_equation_solver_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equation_solver',
            name='finalvars',
            field=models.TextField(default=''),
        ),
    ]
